### ISSUE TITLE
HDBSCAN CLustering Optimization

### ISSUE THREAD

**Issue by luethimi** [liliblu/autocluster#1]
Hi!

I tried to implement a HDBSCAN parameter optimization. 
2 issues occurred:

1. The clus_kwargs are not given to the clusterer (clustering is done using the default values of the HDBSCAN library instead of using the kwargs dict given)
2. I'd like to iterate over different parameter lengths (min_cluster_size has 3 parameters, the rest has only two), which does not work.
Can you tell me if there is a bug in my code or if there is an issue/limitation in the implementation of the hypercluster?
Thanks a lot!

params_to_opt = {
'min_cluster_size': [17,18,19],
'min_samples': [1,2],
'cluster_selection_epsilon': [1,2]
}

kwargs = {
'metric':'euclidean',
'cluster_selection_method':'leaf'
}

clusterer = hypercluster.classes.AutoClusterer(clusterer_name='HDBSCAN', 
                                                                          params_to_optimize=params_to_opt, 
                                                                          clus_kwargs=kwargs)

clusterer.fit(data).evaluate(methods=['number_of_clusters'])

**Comment by tobsecret** [comment]
Have you tried this with the snakemake pipeline? Does it work with that?
Not a maintainer of this project myself but taking a peek at the source code to see if there's an easy explanation for why you're not getting your expected result.

**Comment by tobsecret** [comment]
@luethimi can you please include the outputs that tell you the following is true?

> 1. The clus_kwargs are not given to the clusterer (clustering is done using the default values of the HDBSCAN library instead of using the kwargs dict given)
> 2. I'd like to iterate over different parameter lengths (min_cluster_size has 3 parameters, the rest has only two), which does not work.

**Comment by luethimi** [comment]
Thanks for your help!

After restarting my computer the second issue seems to be gone... It stated 
`ValueError: Length of values does not match length of index`
but it seems to be solved.

However, for the first issue:
When I use the parameters given in the example, i get the following result in the evaluation_df 
(example for the combination 'min_cluster_size' = 19, 'min_samples' = 1 and 'cluster_selection_epsilon' = 1 and the given clus_kwargs):

```
                     HDBSCAN;min_cluster_size-19;min_samples-1;cluster_selection_epsilon-1
methods                                                                                  
number_of_clusters                                                  2         
```           

But when I use the following parameters (integrating the kwargs, that should be constant, into the parameter dict):

```
>         params_to_opt = {
>             'min_cluster_size': [19],
>             'min_samples': [1],
>             'cluster_selection_epsilon': [1],
>             'metric': ['euclidean'],
>             'cluster_selection_method': ['leaf']
>         }
```
The output is

```
                     HDBSCAN;min_cluster_size-19;min_samples-1;cluster_selection_epsilon-1;metric-euclidean;cluster_selection_method-leaf
methods                                                                                                                                 
number_of_clusters                                                  6                                                                   
```
So for the same parameters I get different numbers of clusters found. Double-checking with the plain HDBSCAN package without using hypercluster I saw that the second output is correct (6 clusters should be found), which tells me that there must be an issue with the kwargs dict.

Even

```
        params_to_opt = {
            'min_cluster_size': [19],
            'min_samples': [1],
            'cluster_selection_epsilon': [1]
        }

        kwargs = {
            'metric': 'euclidean',
            'cluster_selection_method': 'leaf'
        }

        clusterer = hypercluster.classes.AutoClusterer(clusterer_name='HDBSCAN',
                                                       params_to_optimize=params_to_opt,
                                                       clus_kwargs=kwargs)
```
only returns 2 clusters, which seems to confirm the issue...

**Comment by luethimi** [comment]
> Have you tried this with the snakemake pipeline? Does it work with that?
> Not a maintainer of this project myself but taking a peek at the source code to see if there's an easy explanation for why you're not getting your expected result.

Haven't tried the snakemake pipeline yet, will try in the next days

**Comment by tobsecret** [comment]
Aaah, gotcha! Thanks for the explanation!
Not sure if I'm reading the source correctly but it's looking like the `clus_kwargs` parameter is just ignored. It's mentioned in [line 103 of classes.py](https://github.com/liliblu/hypercluster/blob/dev/hypercluster/classes.py#L103) and then never mentioned again, and self is also not passed to any other function outside `AutoClusterer`. 
Paging @liliblu for assistance.

For now it looks like just popping the constants into `params_to_opt` should work as a workaround, while we'll figure out a fix.

**Comment by luethimi** [comment]
Nice! Thanks a lot for your effort!!

I tried your proposed workaround... and issue 2 just came back.

So, using the following (simply copying the constant values in the params_to_opt)

```
        params_to_opt = {
            'min_cluster_size': [17, 18, 19],
            'min_samples': [1, 2],
            'cluster_selection_epsilon': [1, 2],
            'metric': ['euclidean'],
            'cluster_selection_method': ['leaf']
        }

        clusterer = hypercluster.classes.AutoClusterer(clusterer_name='HDBSCAN',
                                                       params_to_optimize=params_to_opt)
```

gives the output:
`ValueError: Length of values (1) does not match length of index (12)`

Using the following the code runs without an error concerning issue 2 (so I think having different parameter list lengths is OK):

```
        params_to_opt = {
            'min_cluster_size': [17, 18, 19],
            'min_samples': [1, 2],
            'cluster_selection_epsilon': [1, 2]
        }
```

But using this (only one value for cluster_selection_epsilon):

```
        params_to_opt = {
            'min_cluster_size': [17, 18, 19],
            'min_samples': [1, 2],
            'cluster_selection_epsilon': [1]
        }
```
gives the same output error:
`ValueError: Length of values (1) does not match length of index (6)`

I conclude that giving a constant value in the params_to_opt does not work as expected...

**Comment by tobsecret** [comment]
Can you please post the full traceback? thank you

**Comment by liliblu** [comment]
Hi all, this tool should be maintained on the ruggles lab account (https://github.com/ruggleslab/hypercluster)
I just mirrored it there rather than forked so that it can be public, sorry if that was an issue before.
