### ISSUE TITLE
Calculating number of conditions in AutoClusterer

### ISSUE THREAD

**Issue by tobsecret** [liliblu/autocluster#2]
Not sure I'm understanding the source correctly,  but I think I found something funky-looking in [line 141 of classes.py](https://github.com/liliblu/hypercluster/blob/dev/hypercluster/classes.py#L141). Not sure if I'm understanding it correctly but it looks like there's a typo there when calculating the total number of conditions. Instead of:
```
conditions *= conditions * len(possible_values)
```
which would for a set of 2,3,4 conditions result in: (1*2)*(1*2*3)*(1*2*3*4) conditions

It should be 
```
conditions *=  len(possible_values)
```
which would result in: 1*2*3*4 conditions

**Comment by liliblu** [comment]
Just for posterity, this tool should be maintained on the ruggles lab account (https://github.com/ruggleslab/hypercluster), closing issues here
